import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { getAllPosts } from '@/lib/mdx';
import { getReadyAdapters } from '@/lib/catalog/adapters';
import { getCompareEntries } from '@/lib/compare/data';
import { getAllSeedItems } from '@/lib/ask-seed';
import { getBenchmarkSuite } from '@/lib/benchmarks/data';
import {
  buildSitemapUrls,
  buildSitemapXml,
  toW3CDate,
  type SitemapAdapterRef,
  type SitemapBenchmarkSuite,
  type SitemapCompareEntry,
  type SitemapPost,
  type SitemapSeedItem,
} from '@/lib/sitemap';

/**
 * Module-level cache for content-mtime lookups. The sitemap route can
 * be invoked multiple times per request lifecycle (HEAD + GET, ETag
 * probe); a single fs.stat per source file is enough.
 */
const mtimeCache = new Map<string, string>();

/**
 * Build-time manifest of source-file mtimes (generated by
 * `scripts/build-source-mtimes.mjs` during prebuild). Required because
 * in Next.js standalone production the `app/*.tsx` and `lib/*.ts`
 * source files are NOT shipped in the bundle, so a runtime `fs.stat`
 * on those paths fails and the sitemap drops the lastmod field. The
 * manifest is committed to `data/`, which IS traced into standalone,
 * so the route always has a deterministic lastmod for every URL class.
 *
 * Read once on first lookup and cached. Soft-fails to an empty map if
 * the manifest is missing (e.g. fresh checkout, no prebuild yet): the
 * fs.stat fallback below covers dev mode, and the buildAt fallback
 * covers everything else. Never returns `undefined` - that was the bug
 * this manifest exists to fix (audit 2026-05-21, F-007).
 */
type SourceMtimeManifest = {
  version: number;
  builtAt: string;
  mtimes: Record<string, string | null>;
};

let _manifestCache: SourceMtimeManifest | null = null;

async function loadSourceMtimes(): Promise<SourceMtimeManifest> {
  if (_manifestCache) return _manifestCache;
  const manifestPath = path.join(process.cwd(), 'data', 'source-mtimes.json');
  try {
    const raw = await fs.readFile(manifestPath, 'utf8');
    _manifestCache = JSON.parse(raw) as SourceMtimeManifest;
  } catch {
    /* No manifest available (fresh checkout, no prebuild). Empty map
       + today's build-at means every route still gets a lastmod. */
    _manifestCache = {
      version: 1,
      builtAt: toW3CDate(new Date()),
      mtimes: {},
    };
  }
  return _manifestCache;
}

/**
 * Resolve a deterministic lastmod for a route. Lookup order:
 *
 *   1. `data/source-mtimes.json` - the build-time manifest. SoT in
 *      production because the standalone bundle doesn't ship source
 *      files; everything else is a dev-mode or fresh-checkout
 *      fallback.
 *   2. `fs.stat(abs).mtime` - works in `next dev` where the whole
 *      repo is on disk. Skipped silently if the file is missing
 *      (which is the normal case in standalone).
 *   3. Manifest `builtAt` - the prebuild step's day-precision date,
 *      so even if every other path fails the route still emits a
 *      lastmod. Strictly better than `undefined`: a moving-target
 *      build-date is still a real edit signal for the deploy, and
 *      `<lastmod>` is required for crawlers to weight re-crawl
 *      priority.
 *
 * Each candidate is a project-relative path. Ordering matters: data
 * files come before page.tsx because edits to data are the relevant
 * content-mtime signal for crawler freshness.
 *
 * Results are cached in `mtimeCache` so repeat lookups skip the work.
 */
async function lastModFromSource(
  candidates: readonly string[],
): Promise<string> {
  const manifest = await loadSourceMtimes();
  for (const rel of candidates) {
    const cached = mtimeCache.get(rel);
    if (cached !== undefined) return cached;
    /* Manifest first - SoT in production. */
    const fromManifest = manifest.mtimes[rel];
    if (fromManifest) {
      mtimeCache.set(rel, fromManifest);
      return fromManifest;
    }
    /* fs.stat fallback for `next dev`. */
    try {
      const abs = path.join(process.cwd(), rel);
      const stat = await fs.stat(abs);
      const formatted = toW3CDate(stat.mtime);
      mtimeCache.set(rel, formatted);
      return formatted;
    } catch {
      /* try next candidate */
    }
  }
  /* Manifest's builtAt is the last-resort lastmod. Never return
     undefined: every URL must ship a lastmod (audit 2026-05-21). */
  return manifest.builtAt;
}

function computeEtag(body: string): string {
  return `"${createHash('sha1').update(body).digest('hex')}"`;
}

async function gatherInputs() {
  const manifest = await loadSourceMtimes();
  const posts = await getAllPosts();
  const sitemapPosts: SitemapPost[] = posts.map((p) => ({
    slug: p.slug,
    fm: { date: p.fm.date, dateModified: p.fm.dateModified },
  }));

  /* The catalogue + ask-seed + benchmark data files are each behind a
     try/catch: missing or unparseable files degrade gracefully to an
     empty URL slice rather than breaking the whole sitemap. The
     prebuild step regenerates them; this only triggers on a fresh
     checkout with no prebuild yet. */
  let seedItems: SitemapSeedItem[] = [];
  try {
    seedItems = (await getAllSeedItems()).map((i) => ({ slug: i.slug }));
  } catch {
    /* ask-seed.json missing or unparseable; skip the leaf entries. */
  }

  let readyAdapters: SitemapAdapterRef[] = [];
  try {
    readyAdapters = (await getReadyAdapters()).map((a) => ({
      slug: a.slug,
      verified: a.verified,
    }));
  } catch {
    /* extract-adapters has not yet been run; skip /vs/* entries. */
  }

  let compareEntries: SitemapCompareEntry[] = [];
  try {
    compareEntries = (await getCompareEntries()).map((e) => ({
      slug: e.slug,
      verified: e.verified,
    }));
  } catch {
    /* adapters-meta.json missing or unreadable; skip /compare/* entries. */
  }

  let benchmarkSuite: SitemapBenchmarkSuite | null = null;
  try {
    const suite = await getBenchmarkSuite();
    benchmarkSuite = { dateModified: suite.dateModified };
  } catch {
    /* Benchmark data file missing; skip /benchmarks/* entries. */
  }

  return {
    posts: sitemapPosts,
    seedItems,
    readyAdapters,
    compareEntries,
    benchmarkSuite,
    lastModFromSource,
    buildAt: manifest.builtAt,
  };
}

export async function GET(request: Request): Promise<Response> {
  const inputs = await gatherInputs();
  const urls = await buildSitemapUrls(inputs);
  const xml = buildSitemapXml(urls);
  const etag = computeEtag(xml);

  const ifNoneMatch = request.headers.get('if-none-match');
  if (ifNoneMatch && ifNoneMatch === etag) {
    return new Response(null, {
      status: 304,
      headers: {
        ETag: etag,
        'Cache-Control': 'public, max-age=300, stale-while-revalidate=86400',
      },
    });
  }

  return new Response(xml, {
    status: 200,
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      ETag: etag,
      'Cache-Control': 'public, max-age=300, stale-while-revalidate=86400',
    },
  });
}
