/**
 * Tests for the `lastmod` invariant on `app/sitemap.xml/route.ts`.
 *
 * The contract - also enforced here - is:
 *   - Every URL the route emits MUST carry a `<lastmod>` element. The
 *     pre-fix prod sitemap dropped lastmod on 35% of URLs because the
 *     Next.js standalone bundle doesn't ship `app/*.tsx` or `lib/*.ts`
 *     and the route used to `fs.stat` those paths at request time.
 *   - The fix introduces `data/source-mtimes.json`, a build-time
 *     manifest generated by `scripts/build-source-mtimes.mjs`. The
 *     manifest's keys are every source path the route references as a
 *     `lastModFromSource(...)` candidate (and the manifest's `builtAt`
 *     is the last-resort fallback so the route never emits a URL
 *     without lastmod).
 *   - lastmod is per-entry-accurate: blog posts use frontmatter
 *     `dateModified` (fallback `date`); generated generated catalogue pages use
 *     the source data file's git mtime; static pages use page.tsx
 *     mtime. The whole sitemap MUST NOT collapse to a single date
 *     when content sources have varied dates.
 *   - Sitemap entries are NOT emitted for routes that serve
 *     `x-robots-tag: noindex` (`/llms.txt`, `/llms-full.txt`,
 *     `/ai.txt`). A sitemap entry for a noindex URL is a
 *     self-cancelling signal and shows up in Search Console as
 *     "Submitted URL marked noindex".
 *
 * What this test covers (without booting Next.js):
 *   - `scripts/build-source-mtimes.mjs` produces a manifest of the
 *     expected shape.
 *   - Every TRACKED_PATHS entry in the script has an mtime value in
 *     the generated manifest (committed `data/source-mtimes.json`).
 *   - The manifest's `mtimes` map covers every `lastModFromSource`
 *     candidate the route uses (regex-scraped from the route file so
 *     a new candidate added to the route without updating the script
 *     fails the test).
 *   - The pure `buildSitemapUrls` helper in `lib/sitemap.ts` produces
 *     varied per-entry lastmod values and omits the noindex routes.
 *
 * These together guarantee the production sitemap can ship a lastmod
 * for every URL class without booting Next.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import {
  buildSitemapUrls,
  buildSitemapXml,
  postLastMod,
  type SitemapPost,
} from '../lib/sitemap.ts';

const repoRoot = process.cwd();

type Manifest = {
  version: number;
  builtAt: string;
  mtimes: Record<string, string | null>;
};

async function loadManifest(): Promise<Manifest> {
  const raw = await readFile(
    path.join(repoRoot, 'data', 'source-mtimes.json'),
    'utf8',
  );
  return JSON.parse(raw) as Manifest;
}

test('source-mtimes manifest has the expected shape', async () => {
  const m = await loadManifest();
  assert.equal(m.version, 1, 'manifest version pinned at 1');
  assert.match(
    m.builtAt,
    /^\d{4}-\d{2}-\d{2}$/,
    'builtAt is W3C day-precision',
  );
  assert.equal(
    typeof m.mtimes,
    'object',
    'mtimes is an object keyed by source path',
  );
  assert.ok(Object.keys(m.mtimes).length > 0, 'mtimes is non-empty');
});

test('every mtime value is W3C day-precision or null', async () => {
  const m = await loadManifest();
  for (const [key, val] of Object.entries(m.mtimes)) {
    if (val === null) continue;
    assert.match(
      val,
      /^\d{4}-\d{2}-\d{2}$/,
      `${key} mtime must be YYYY-MM-DD or null, got ${val}`,
    );
  }
});

test('manifest covers every lastModFromSource candidate in route.ts', async () => {
  const m = await loadManifest();
  const routeSrc = await readFile(
    path.join(repoRoot, 'app', 'sitemap.xml', 'route.ts'),
    'utf8',
  );
  const libSrc = await readFile(
    path.join(repoRoot, 'lib', 'sitemap.ts'),
    'utf8',
  );

  /* Pull every string literal passed inside a `lastModFromSource([...])`
     call across both the route and the lib helper. Regex-scraped
     because parsing TS for this test is overkill; the contract is
     "every candidate path used by sitemap code also appears in the
     manifest." */
  const combined = `${routeSrc}\n${libSrc}`;
  const lastModBlocks = combined.match(/lastModFromSource\(\[[^\]]+\]/g) ?? [];
  assert.ok(
    lastModBlocks.length > 0,
    'sitemap source should call lastModFromSource at least once',
  );

  const candidates = new Set<string>();
  for (const block of lastModBlocks) {
    const literals = block.match(/['"]([^'"]+)['"]/g) ?? [];
    for (const l of literals) {
      candidates.add(l.slice(1, -1));
    }
  }
  assert.ok(
    candidates.size > 0,
    'parsed at least one candidate from sitemap source',
  );

  for (const c of candidates) {
    assert.ok(
      c in m.mtimes,
      `sitemap source references '${c}' as a lastmod source; add it to TRACKED_PATHS in scripts/build-source-mtimes.mjs`,
    );
  }
});

/* ---------- per-entry lastmod accuracy (issue #41) ---------- */

const FIXTURE_BUILD_AT = '2026-05-21';

function makePost(over: Partial<SitemapPost> & { slug: string }): SitemapPost {
  return {
    slug: over.slug,
    fm: {
      date: over.fm?.date ?? '2026-01-01',
      dateModified: over.fm?.dateModified,
    },
  };
}

/* Fixture lastModFromSource resolver: maps each candidate path to a
   distinct date so the test can detect a "single-date collapse"
   regression where every entry pulls today's date. */
const FIXTURE_MTIMES: Record<string, string> = {
  'app/page.tsx': '2026-04-01',
  'app/cli-quickstart/page.tsx': '2026-04-05',
  'app/why-bernstein/page.tsx': '2026-04-10',
  'app/cost/page.tsx': '2026-04-12',
  'app/sponsors/page.tsx': '2026-04-15',
  'app/ask/page.tsx': '2026-04-18',
  'app/tools/agent-md-bench/page.tsx': '2026-04-20',
  'app/tools/orchestra/page.tsx': '2026-04-22',
  'data/ask-seed.json': '2026-04-25',
  'app/q/page.tsx': '2026-04-26',
  'app/spec-driven/page.tsx': '2026-04-28',
  'data/adapters.json': '2026-05-01',
  'app/vs/page.tsx': '2026-05-02',
  'lib/compare/data.ts': '2026-05-04',
  'app/compare/page.tsx': '2026-05-05',
};

function fixtureLastModResolver(): (
  candidates: readonly string[],
) => Promise<string> {
  return async (candidates) => {
    for (const c of candidates) {
      const v = FIXTURE_MTIMES[c];
      if (v) return v;
    }
    return FIXTURE_BUILD_AT;
  };
}

test('blog entries lastmod comes from frontmatter, not build date', async () => {
  const oldPost = makePost({
    slug: 'introducing-bernstein',
    fm: { date: '2026-03-29' },
  });
  const editedPost = makePost({
    slug: 'getting-started',
    fm: { date: '2026-04-14', dateModified: '2026-05-13' },
  });

  const lastModFromSource = fixtureLastModResolver();
  const urls = await buildSitemapUrls({
    posts: [oldPost, editedPost],
    seedItems: [],
    readyAdapters: [],
    compareEntries: [],
    benchmarkSuite: null,
    lastModFromSource,
    buildAt: FIXTURE_BUILD_AT,
  });

  const intro = urls.find(
    (u) => u.loc === 'https://bernstein.run/blog/introducing-bernstein',
  );
  const gettingStarted = urls.find(
    (u) => u.loc === 'https://bernstein.run/blog/getting-started',
  );

  assert.ok(intro, 'introducing-bernstein entry present');
  assert.ok(gettingStarted, 'getting-started entry present');

  assert.equal(
    intro!.lastmod,
    '2026-03-29',
    'intro post lastmod must be the frontmatter date, not the build date',
  );
  assert.equal(
    gettingStarted!.lastmod,
    '2026-05-13',
    'edited post lastmod must be the frontmatter dateModified',
  );
  assert.notEqual(
    intro!.lastmod,
    FIXTURE_BUILD_AT,
    'months-old post must not stamp today as lastmod',
  );
});

test('sitemap has at least one entry with lastmod older than today', async () => {
  /* Re-renders the regression in issue #41: every URL collapsing to
     today's date. With per-entry sourcing, at least one entry must
     report a date older than the build day. */
  const oldPost = makePost({
    slug: 'introducing-bernstein',
    fm: { date: '2026-03-29' },
  });
  const lastModFromSource = fixtureLastModResolver();

  const urls = await buildSitemapUrls({
    posts: [oldPost],
    seedItems: [],
    readyAdapters: [],
    compareEntries: [],
    benchmarkSuite: null,
    lastModFromSource,
    buildAt: FIXTURE_BUILD_AT,
  });

  const older = urls.filter((u) => u.lastmod < FIXTURE_BUILD_AT);
  assert.ok(
    older.length > 0,
    `expected at least one entry with lastmod older than ${FIXTURE_BUILD_AT}, got ${urls
      .map((u) => `${u.loc}=${u.lastmod}`)
      .join(', ')}`,
  );
});

test('sitemap entries carry varied lastmod values (no single-date collapse)', async () => {
  const posts: SitemapPost[] = [
    makePost({ slug: 'a', fm: { date: '2026-01-15' } }),
    makePost({
      slug: 'b',
      fm: { date: '2026-02-20', dateModified: '2026-03-01' },
    }),
  ];
  const urls = await buildSitemapUrls({
    posts,
    seedItems: [{ slug: 'q-one' }, { slug: 'q-two' }],
    readyAdapters: [{ slug: 'aider' }, { slug: 'cursor' }],
    compareEntries: [{ slug: 'aider' }, { slug: 'cursor' }],
    benchmarkSuite: { dateModified: '2026-05-10' },
    lastModFromSource: fixtureLastModResolver(),
    buildAt: FIXTURE_BUILD_AT,
  });

  const distinct = new Set(urls.map((u) => u.lastmod));
  assert.ok(
    distinct.size > 1,
    `sitemap lastmod must NOT collapse to a single date; got ${distinct.size} distinct values: ${[...distinct].join(', ')}`,
  );
});

/* ---------- noindex URLs are excluded (issue #42) ---------- */

test('sitemap output does NOT list noindex discovery files', async () => {
  const urls = await buildSitemapUrls({
    posts: [makePost({ slug: 'a' })],
    seedItems: [],
    readyAdapters: [],
    compareEntries: [],
    benchmarkSuite: null,
    lastModFromSource: fixtureLastModResolver(),
    buildAt: FIXTURE_BUILD_AT,
  });

  const locs = urls.map((u) => u.loc);
  const forbidden = [
    'https://bernstein.run/llms.txt',
    'https://bernstein.run/llms-full.txt',
    'https://bernstein.run/ai.txt',
  ];
  for (const f of forbidden) {
    assert.equal(
      locs.includes(f),
      false,
      `${f} serves x-robots-tag noindex and MUST NOT appear in sitemap.xml (issue #42)`,
    );
  }

  /* Also check the XML rendering layer to catch any accidental
     hard-coding outside buildSitemapUrls. */
  const xml = buildSitemapXml(urls);
  for (const f of forbidden) {
    assert.equal(
      xml.includes(`<loc>${f}</loc>`),
      false,
      `${f} must not appear in the rendered sitemap xml`,
    );
  }
});

test('route.ts source does not advertise noindex discovery files', async () => {
  /* Belt-and-braces: even if a future refactor inlines URLs back into
     the route handler, the source must not contain the noindex URLs. */
  const routeSrc = await readFile(
    path.join(repoRoot, 'app', 'sitemap.xml', 'route.ts'),
    'utf8',
  );
  const libSrc = await readFile(
    path.join(repoRoot, 'lib', 'sitemap.ts'),
    'utf8',
  );
  const combined = `${routeSrc}\n${libSrc}`;

  for (const banned of ['/llms.txt', '/llms-full.txt', '/ai.txt']) {
    /* Reject the bare URL-suffix literal inside a SitemapUrl entry.
       Comment-only mentions (explaining why they are absent) are
       allowed; we only forbid the path appearing where a sitemap
       url could ship it. */
    const sitemapEntry = new RegExp(
      `loc:\\s*\`?[^\`]*${banned.replace('.', '\\.')}`,
    );
    assert.equal(
      sitemapEntry.test(combined),
      false,
      `sitemap source must not emit ${banned} as a <url> (it serves x-robots-tag noindex)`,
    );
  }
});

/* ---------- postLastMod direct unit test ---------- */

test('postLastMod returns frontmatter dateModified when present', async () => {
  const result = await postLastMod(
    { slug: 'x', fm: { date: '2026-01-01', dateModified: '2026-03-15' } },
    FIXTURE_BUILD_AT,
  );
  assert.equal(result, '2026-03-15');
});

test('postLastMod falls back to frontmatter date when dateModified absent', async () => {
  const result = await postLastMod(
    { slug: 'x', fm: { date: '2026-02-10' } },
    FIXTURE_BUILD_AT,
  );
  assert.equal(result, '2026-02-10');
});

test('postLastMod falls back to buildAt only when frontmatter is unparseable', async () => {
  const result = await postLastMod(
    { slug: 'x', fm: { date: 'not-a-date' } },
    FIXTURE_BUILD_AT,
  );
  assert.equal(result, FIXTURE_BUILD_AT);
});
