import type { Metadata } from 'next';
import { Nav } from '@/components/landing/Nav';
import { Footer } from '@/components/landing/Footer';
import { StaticPageBreadcrumb } from '@/components/seo/BreadcrumbListJsonLd';

const SITE_URL = 'https://bernstein.run';
const LAST_UPDATED = '2026-05-08';

export const metadata: Metadata = {
  title: 'Terms',
  description:
    'Rules for using bernstein.run: no scraping abuse, no warranties on the open-source project, Israeli law applies. Plain English.',
  alternates: { canonical: `${SITE_URL}/terms` },
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main className="blog-post-layout">
        <article className="blog-post">
          <header className="blog-post-header">
            <h1>Terms of Use</h1>
            <p className="blog-post-meta">
              <time dateTime={LAST_UPDATED}>Last updated: {LAST_UPDATED}</time>
            </p>
          </header>

          <div className="prose">
            <h2>Scope</h2>
            <p>
              These terms cover the bernstein.run website and the public
              endpoints it exposes (RSS, sitemaps, the blog, the docs assistant
              at <code>/ask</code>). The Bernstein software itself is licensed
              under <a href="https://www.apache.org/licenses/LICENSE-2.0" rel="noopener">Apache 2.0</a>;
              that licence governs the code, not this page.
            </p>

            <h2>What you can do</h2>
            <p>
              Read, link to, and quote anything on this site. Cite us with a
              link back. Subscribe to the RSS feed in any reader. Use the docs
              assistant at <code>/ask</code> at a sane request rate.
            </p>

            <h2>What you cannot do</h2>
            <ul>
              <li>
                Scrape the site at high rate. We rate-limit per IP. Sustained
                abuse will get the IP blocked.
              </li>
              <li>
                Try to break the docs assistant - prompt-injection attempts,
                attempts to extract the system prompt, attempts to use it as
                a free LLM proxy. These are logged and blocked.
              </li>
              <li>
                Send malicious traffic (vuln scanners run for free practice,
                payloads, bot armies). We forward repeat offenders to their
                hosting provider.
              </li>
              <li>
                Reupload our content as your own. Quoting is fine; copying the
                whole post and removing attribution is not.
              </li>
            </ul>

            <h2>No warranty</h2>
            <p>
              The site, the assistant, and the open-source Bernstein project
              are provided as is. The blog posts describe technical decisions
              and trade-offs; following them is your call. We are not liable
              for downstream outcomes - broken builds, lost time, or bills run
              up by AI agents you orchestrate using the project.
            </p>

            <h2>The assistant</h2>
            <p>
              <code>/ask</code> answers questions about the Bernstein
              documentation. Answers are generated by an LLM and can be wrong
              or out of date. Verify anything load-bearing against the
              repository before relying on it.
            </p>

            <h2>Email opt-in</h2>
            <p>
              If you subscribe to email updates, you can unsubscribe at any
              time from the link at the bottom of any email. We do not sell or
              share the list.
            </p>

            <h2>Governing law</h2>
            <p>
              These terms are governed by the law of the State of Israel.
              Disputes are venued in the competent courts of Tel Aviv-Yafo. If
              any clause here is unenforceable, the rest still stand.
            </p>

            <h2>Changes</h2>
            <p>
              If these terms change, the &ldquo;Last updated&rdquo; date moves
              and a note goes on the blog. Continued use of the site after
              that means you accept the change.
            </p>

            <h2>Contact</h2>
            <p>
              Questions, takedown requests, abuse reports:{' '}
              <a href="mailto:forte@bernstein.run">forte@bernstein.run</a>.
            </p>
          </div>
        </article>
      </main>
      <Footer />
      <StaticPageBreadcrumb name="Terms" slug="/terms" />
    </>
  );
}
